### ISSUE TITLE
Library cannot use bind on the website with mootools

### ISSUE THREAD

**Issue by drdmitry** [snapwich/fun-hooks#1]
There is a website, which has mootools library loaded on the page.
When using Prebid 2.0 (with fun-hooks) - getting an error when the bind function is used.
The problem is that mootools re-defining the Function.prototype.bind.
See screenshot for some details.
Example (sample page) to be created.
What would you suggest for a fix? There is no access to change the website content (remove mootools).

![image](https://user-images.githubusercontent.com/4129726/52507683-8e3db700-2bf2-11e9-9285-7b8572f33902.png)

**Comment by snapwich** [comment]
Do you have a test URL I could see the live error at?
